language: python

python:
  - 2.6
  - 2.7
  - pypy

before_install:
  - pip install --use-mirrors pathtools argh pyyaml unittest2 coverage

install: python setup.py install

script:
  - coverage erase
  - coverage run run_tests.py
  - coverage report -m
